export const GET_ALL_GROUPS = "GET_ALL_GROUPS";
export const ADD_GROUP = "ADD_GROUP";
export const GET_GROUP = "GET_GROUP";
export const REMOVE_GROUP = "REMOVE_GROUP";
export const ADD_VALUE_TO_GROUP = "ADD_VALUE_TO_GROUP";
export const REMOVE_VALUE_FROM_GROUP = "REMOVE_VALUE_FROM_GROUP";
export const UPDATE_VALUE_FROM_GROUP = "UPDATE_VALUE_FROM_GROUP";